"""PowerPoint generation from chat content."""

import io
import re
from pptx import Presentation
from pptx.util import Inches, Pt, Emu
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN


_RED = RGBColor(0xCC, 0x00, 0x00)
_DARK = RGBColor(0x1A, 0x1A, 0x2E)
_WHITE = RGBColor(0xFF, 0xFF, 0xFF)
_GRAY = RGBColor(0x6B, 0x72, 0x80)


def _add_title_slide(prs: Presentation, title: str, subtitle: str):
    slide = prs.slides.add_slide(prs.slide_layouts[6])  # blank
    # Dark background
    bg = slide.background.fill
    bg.solid()
    bg.fore_color.rgb = _DARK

    # Title
    txBox = slide.shapes.add_textbox(Inches(0.8), Inches(2), Inches(8.4), Inches(1.5))
    tf = txBox.text_frame
    tf.word_wrap = True
    p = tf.paragraphs[0]
    p.text = title
    p.font.size = Pt(36)
    p.font.bold = True
    p.font.color.rgb = _WHITE
    p.alignment = PP_ALIGN.LEFT

    # Subtitle
    p2 = tf.add_paragraph()
    p2.text = subtitle
    p2.font.size = Pt(16)
    p2.font.color.rgb = RGBColor(0x8B, 0xE9, 0xFD)
    p2.alignment = PP_ALIGN.LEFT

    # Red accent bar
    slide.shapes.add_shape(
        1, Inches(0.8), Inches(1.8), Inches(2), Emu(40000)
    ).fill.solid()
    slide.shapes[-1].fill.fore_color.rgb = _RED
    slide.shapes[-1].line.fill.background()


def _parse_sections(text: str) -> list[dict]:
    """Split markdown text into sections by headings."""
    sections = []
    current = {"title": "", "bullets": []}
    for line in text.split("\n"):
        line = line.strip()
        if not line:
            continue
        heading = re.match(r'^#{1,3}\s+(.+)', line)
        if heading:
            if current["title"] or current["bullets"]:
                sections.append(current)
            current = {"title": heading.group(1).strip("*"), "bullets": []}
        elif line.startswith(("- ", "* ", "• ")):
            bullet = re.sub(r'^[-*•]\s*', '', line)
            bullet = re.sub(r'\*\*(.+?)\*\*', r'\1', bullet)  # strip bold
            current["bullets"].append(bullet)
        elif line.startswith(("1.", "2.", "3.", "4.", "5.", "6.", "7.", "8.", "9.")):
            bullet = re.sub(r'^\d+[\.\)]\s*', '', line)
            bullet = re.sub(r'\*\*(.+?)\*\*', r'\1', bullet)
            current["bullets"].append(bullet)
        else:
            clean = re.sub(r'\*\*(.+?)\*\*', r'\1', line)
            clean = re.sub(r'```.*?```', '', clean, flags=re.DOTALL)
            if clean.strip():
                current["bullets"].append(clean)

    if current["title"] or current["bullets"]:
        sections.append(current)
    return sections


def _add_content_slide(prs: Presentation, title: str, bullets: list[str]):
    slide = prs.slides.add_slide(prs.slide_layouts[6])  # blank

    # Red top bar
    bar = slide.shapes.add_shape(1, 0, 0, prs.slide_width, Emu(80000))
    bar.fill.solid()
    bar.fill.fore_color.rgb = _RED
    bar.line.fill.background()

    # Title
    txBox = slide.shapes.add_textbox(Inches(0.6), Inches(0.4), Inches(8.8), Inches(0.8))
    tf = txBox.text_frame
    tf.word_wrap = True
    p = tf.paragraphs[0]
    p.text = title
    p.font.size = Pt(24)
    p.font.bold = True
    p.font.color.rgb = _DARK

    # Bullets
    if bullets:
        txBox2 = slide.shapes.add_textbox(Inches(0.6), Inches(1.4), Inches(8.8), Inches(5))
        tf2 = txBox2.text_frame
        tf2.word_wrap = True
        for i, b in enumerate(bullets[:12]):  # max 12 bullets per slide
            p = tf2.paragraphs[0] if i == 0 else tf2.add_paragraph()
            p.text = b[:200]  # truncate long bullets
            p.font.size = Pt(14)
            p.font.color.rgb = RGBColor(0x37, 0x41, 0x51)
            p.space_after = Pt(6)
            p.level = 0


def generate_pptx(slides_data: list[dict]) -> bytes:
    """Generate a PPTX from structured slide data.

    slides_data: [{"title": str, "content": str}, ...]
    Each content is markdown text that gets parsed into sections/bullets.
    """
    prs = Presentation()
    prs.slide_width = Inches(10)
    prs.slide_height = Inches(5.625)  # 16:9

    # Title slide
    main_title = slides_data[0]["title"] if slides_data else "Ricoh AI Presentation"
    _add_title_slide(prs, main_title, "Generated by Ricoh AI Agent")

    for item in slides_data:
        sections = _parse_sections(item.get("content", ""))
        if not sections:
            _add_content_slide(prs, item["title"], [item.get("content", "")[:500]])
            continue
        for sec in sections:
            title = sec["title"] or item["title"]
            _add_content_slide(prs, title, sec["bullets"])

    buf = io.BytesIO()
    prs.save(buf)
    return buf.getvalue()
