"""LLM-powered PowerPoint generation — uses Claude to structure slides, python-pptx to render."""

import io
import os
import re
import json
import logging
from pptx import Presentation
from pptx.util import Inches, Pt, Emu
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN

# --- Ricoh brand palette ---
_RED = RGBColor(0xCC, 0x00, 0x00)
_DARK = RGBColor(0x1A, 0x1A, 0x2E)
_WHITE = RGBColor(0xFF, 0xFF, 0xFF)
_LIGHT = RGBColor(0xF7, 0xF8, 0xFA)
_TEXT = RGBColor(0x1F, 0x29, 0x37)
_MUTED = RGBColor(0x6B, 0x72, 0x80)
_BLUE = RGBColor(0x3B, 0x82, 0xF6)
_GREEN = RGBColor(0x10, 0xB9, 0x81)

SLIDE_SCHEMA_PROMPT = """You are a presentation designer. Convert the following content into a structured JSON array of slides for a professional enterprise presentation.

RULES:
- Each slide must have: "type" (title|section|bullets|numbered|table|quote|closing), "title" (string), and type-specific fields
- "bullets" type: include "items" array of strings (max 6 per slide, split into multiple slides if needed)
- "numbered" type: include "items" array of strings (max 6 per slide)
- "table" type: include "headers" array and "rows" array of arrays
- "section" type: just "title" and optional "subtitle" — used as dark divider between topics
- "quote" type: include "text" and optional "author"
- "title" type: "title" and "subtitle" — only for the first slide
- "closing" type: "title" and "subtitle" — only for the last slide
- Keep text concise: max 15 words per bullet point, rewrite if needed
- Create 5-15 slides depending on content length
- Group related points logically
- Add a section divider slide before each major topic change
- First slide must be type "title", last must be type "closing"
- Write in the SAME LANGUAGE as the input content

Content to convert:
{content}

Reply with ONLY valid JSON array, no markdown wrapper."""


def _call_llm(content: str) -> list[dict]:
    """Ask Claude to structure content into slides."""
    try:
        from langchain_anthropic import ChatAnthropic
        llm = ChatAnthropic(
            model=os.environ["AZURE_AI_CHAT_DEPLOYMENT"],
            api_key=os.environ["AZURE_AI_KEY"],
            base_url=os.environ["AZURE_AI_ENDPOINT"],
            temperature=0, max_tokens=4096,
        )
        result = llm.invoke(SLIDE_SCHEMA_PROMPT.format(content=content[:6000]))
        raw = result.content.strip()
        # Extract JSON array
        match = re.search(r'\[.*\]', raw, re.DOTALL)
        if match:
            return json.loads(match.group())
    except Exception as e:
        logging.warning(f"LLM slide structuring failed: {e}")
    return None


def _fallback_parse(title: str, content: str) -> list[dict]:
    """Simple fallback parser when LLM is unavailable."""
    slides = [{"type": "title", "title": title, "subtitle": "Generated by Ricoh AI Agent"}]
    current_title = title
    current_items = []

    for line in content.split("\n"):
        s = line.strip()
        if not s or s.startswith("```"):
            continue
        heading = re.match(r'^#{1,3}\s+(.+)', s)
        if heading:
            if current_items:
                slides.append({"type": "bullets", "title": current_title, "items": current_items[:6]})
                if len(current_items) > 6:
                    slides.append({"type": "bullets", "title": current_title + " (cont.)", "items": current_items[6:12]})
                current_items = []
            current_title = re.sub(r'\*\*(.+?)\*\*', r'\1', heading.group(1))
            slides.append({"type": "section", "title": current_title})
            continue
        bullet = re.match(r'^[-*•]\s+(.+)', s)
        if bullet:
            current_items.append(re.sub(r'\*\*(.+?)\*\*', r'\1', bullet.group(1))[:120])
            continue
        num = re.match(r'^\d+[\.\)]\s*(.+)', s)
        if num:
            current_items.append(re.sub(r'\*\*(.+?)\*\*', r'\1', num.group(1))[:120])
            continue
        if s and not s.startswith("|") and not s.startswith("---"):
            current_items.append(re.sub(r'\*\*(.+?)\*\*', r'\1', s)[:120])

    if current_items:
        slides.append({"type": "bullets", "title": current_title, "items": current_items[:6]})
        if len(current_items) > 6:
            slides.append({"type": "bullets", "title": current_title + " (cont.)", "items": current_items[6:12]})

    slides.append({"type": "closing", "title": "Grazie", "subtitle": "Ricoh AI Agent · PoC Demo"})
    # Remove back-to-back sections (keep only the last one)
    cleaned = []
    for i, s in enumerate(slides):
        if s["type"] == "section" and i + 1 < len(slides) and slides[i + 1].get("type") == "section":
            continue
        cleaned.append(s)
    return cleaned


# --- Slide renderers ---

def _bar(slide, prs, color=_RED, h=80000):
    b = slide.shapes.add_shape(1, 0, 0, prs.slide_width, Emu(h))
    b.fill.solid(); b.fill.fore_color.rgb = color; b.line.fill.background()


def _footer(slide, text="Ricoh AI Agent"):
    ft = slide.shapes.add_textbox(Inches(0.5), Inches(5.1), Inches(9), Inches(0.4))
    p = ft.text_frame.paragraphs[0]
    p.text = text
    p.font.size = Pt(8); p.font.color.rgb = _MUTED; p.alignment = PP_ALIGN.RIGHT


def _render_title(prs, data):
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    bg = slide.background.fill; bg.solid(); bg.fore_color.rgb = _DARK

    # Red accent
    a = slide.shapes.add_shape(1, Inches(0.8), Inches(1.9), Inches(1.2), Emu(50000))
    a.fill.solid(); a.fill.fore_color.rgb = _RED; a.line.fill.background()

    tx = slide.shapes.add_textbox(Inches(0.8), Inches(2.1), Inches(8.4), Inches(2))
    tf = tx.text_frame; tf.word_wrap = True
    p = tf.paragraphs[0]
    p.text = data.get("title", "")
    p.font.size = Pt(36); p.font.bold = True; p.font.color.rgb = _WHITE
    p2 = tf.add_paragraph()
    p2.text = data.get("subtitle", "")
    p2.font.size = Pt(16); p2.font.color.rgb = RGBColor(0x8B, 0xE9, 0xFD)
    p2.space_before = Pt(16)

    _footer(slide, "Powered by Claude Sonnet 4 · LangGraph · pgvector")


def _render_section(prs, data):
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    bg = slide.background.fill; bg.solid(); bg.fore_color.rgb = _DARK

    a = slide.shapes.add_shape(1, Inches(0.8), Inches(2.2), Emu(800000), Emu(50000))
    a.fill.solid(); a.fill.fore_color.rgb = _RED; a.line.fill.background()

    tx = slide.shapes.add_textbox(Inches(0.8), Inches(2.45), Inches(8.4), Inches(1.2))
    tf = tx.text_frame; tf.word_wrap = True
    p = tf.paragraphs[0]
    p.text = data.get("title", "")
    p.font.size = Pt(30); p.font.bold = True; p.font.color.rgb = _WHITE
    if data.get("subtitle"):
        p2 = tf.add_paragraph()
        p2.text = data["subtitle"]
        p2.font.size = Pt(14); p2.font.color.rgb = _MUTED


def _render_bullets(prs, data, numbered=False):
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    _bar(slide, prs)

    tx = slide.shapes.add_textbox(Inches(0.6), Inches(0.3), Inches(8.8), Inches(0.7))
    p = tx.text_frame.paragraphs[0]
    p.text = data.get("title", "")
    p.font.size = Pt(22); p.font.bold = True; p.font.color.rgb = _DARK

    items = data.get("items", [])
    if not items:
        return

    tx2 = slide.shapes.add_textbox(Inches(0.6), Inches(1.15), Inches(8.8), Inches(4))
    tf = tx2.text_frame; tf.word_wrap = True

    for i, item in enumerate(items[:8]):
        par = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
        text = str(item)[:200]

        # Detect "Bold part — rest" pattern
        m = re.match(r'^(.{3,50}?)\s*[-–—:]\s+(.+)$', text)
        if m:
            r1 = par.add_run()
            r1.text = m.group(1)
            r1.font.size = Pt(14); r1.font.bold = True; r1.font.color.rgb = _DARK
            r2 = par.add_run()
            r2.text = " — " + m.group(2)
            r2.font.size = Pt(14); r2.font.color.rgb = _TEXT
        else:
            prefix = f"{i+1}. " if numbered else "▸ "
            par.text = prefix + text
            par.font.size = Pt(14); par.font.color.rgb = _TEXT

        par.space_after = Pt(6); par.line_spacing = Pt(20)

    _footer(slide)


def _render_table(prs, data):
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    _bar(slide, prs)

    tx = slide.shapes.add_textbox(Inches(0.6), Inches(0.3), Inches(8.8), Inches(0.7))
    p = tx.text_frame.paragraphs[0]
    p.text = data.get("title", "Confronto")
    p.font.size = Pt(22); p.font.bold = True; p.font.color.rgb = _DARK

    headers = data.get("headers", [])
    rows = data.get("rows", [])
    if not headers:
        return

    n_cols = len(headers)
    n_rows = min(len(rows) + 1, 10)
    tbl_shape = slide.shapes.add_table(n_rows, n_cols, Inches(0.4), Inches(1.15), Inches(9.2), Inches(3.8))
    tbl = tbl_shape.table

    for j, h in enumerate(headers):
        cell = tbl.cell(0, j); cell.text = str(h).strip()
        for par in cell.text_frame.paragraphs:
            par.font.size = Pt(11); par.font.bold = True; par.font.color.rgb = _WHITE
        cell.fill.solid(); cell.fill.fore_color.rgb = _DARK

    for i, row in enumerate(rows[:n_rows - 1]):
        for j in range(min(len(row), n_cols)):
            cell = tbl.cell(i + 1, j); cell.text = str(row[j]).strip()
            for par in cell.text_frame.paragraphs:
                par.font.size = Pt(10); par.font.color.rgb = _TEXT
            cell.fill.solid()
            cell.fill.fore_color.rgb = _WHITE if i % 2 == 0 else _LIGHT

    _footer(slide)


def _render_quote(prs, data):
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    bg = slide.background.fill; bg.solid(); bg.fore_color.rgb = _LIGHT

    # Red quote mark
    q = slide.shapes.add_textbox(Inches(0.8), Inches(1.2), Inches(1), Inches(1))
    qp = q.text_frame.paragraphs[0]
    qp.text = "\u201C"
    qp.font.size = Pt(72); qp.font.color.rgb = _RED; qp.font.bold = True

    tx = slide.shapes.add_textbox(Inches(1.2), Inches(1.8), Inches(7.6), Inches(2.5))
    tf = tx.text_frame; tf.word_wrap = True
    p = tf.paragraphs[0]
    p.text = data.get("text", "")[:300]
    p.font.size = Pt(20); p.font.italic = True; p.font.color.rgb = _DARK
    p.line_spacing = Pt(28)

    if data.get("author"):
        p2 = tf.add_paragraph()
        p2.text = "— " + data["author"]
        p2.font.size = Pt(14); p2.font.color.rgb = _MUTED
        p2.space_before = Pt(16)

    _footer(slide)


def _render_closing(prs, data):
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    bg = slide.background.fill; bg.solid(); bg.fore_color.rgb = _DARK

    tx = slide.shapes.add_textbox(Inches(1.5), Inches(1.8), Inches(7), Inches(2))
    tf = tx.text_frame
    p = tf.paragraphs[0]
    p.text = data.get("title", "Grazie")
    p.font.size = Pt(40); p.font.bold = True; p.font.color.rgb = _WHITE
    p.alignment = PP_ALIGN.CENTER
    p2 = tf.add_paragraph()
    p2.text = data.get("subtitle", "Ricoh AI Agent")
    p2.font.size = Pt(14); p2.font.color.rgb = _MUTED
    p2.alignment = PP_ALIGN.CENTER; p2.space_before = Pt(12)


_RENDERERS = {
    "title": _render_title,
    "section": _render_section,
    "bullets": _render_bullets,
    "numbered": lambda prs, d: _render_bullets(prs, d, numbered=True),
    "table": _render_table,
    "quote": _render_quote,
    "closing": _render_closing,
}


def generate_pptx(slides_data: list[dict]) -> bytes:
    """Generate a PPTX from chat content. Uses LLM to structure, python-pptx to render.

    slides_data: [{"title": str, "content": str (markdown)}, ...]
    """
    # Merge all content
    all_content = "\n\n---\n\n".join(
        f"## {s['title']}\n{s['content']}" for s in slides_data if s.get("content")
    )
    main_title = slides_data[0]["title"] if slides_data else "Ricoh AI"

    # Try LLM structuring, fallback to parser
    structured = _call_llm(all_content)
    if not structured or not isinstance(structured, list):
        structured = _fallback_parse(main_title, all_content)

    # Ensure first/last slides
    if not structured or structured[0].get("type") != "title":
        structured.insert(0, {"type": "title", "title": main_title, "subtitle": "Generated by Ricoh AI Agent"})
    if structured[-1].get("type") != "closing":
        structured.append({"type": "closing", "title": "Grazie", "subtitle": "Ricoh AI Agent · PoC Demo"})

    # Render
    prs = Presentation()
    prs.slide_width = Inches(10)
    prs.slide_height = Inches(5.625)

    for slide_def in structured:
        stype = slide_def.get("type", "bullets")
        renderer = _RENDERERS.get(stype, _render_bullets)
        try:
            renderer(prs, slide_def)
        except Exception as e:
            logging.warning(f"Slide render error ({stype}): {e}")

    buf = io.BytesIO()
    prs.save(buf)
    return buf.getvalue()
